### ISSUE TITLE
Features: Display release date of each package; filter by package release date

### ISSUE THREAD

**Issue by andy-maier** [tox-dev/pipdeptree#148]
Since I have run across pipdeptree, it has become the single most important tool for me for analyzing package dependencies when something goes wrong with the dependencies. Kudos to the dev team!!

What I am missing though is the package release date of the installed package to be shown in the output, maybe controlled by an option.

Also, a filter option would be great that lists only those packages from the complete set of packages that have been released recently, say in the last 7 days, or since a specifyable number of days.

The motivation for these two features is that in most of the cases, the reason for a dependency problem is a recently released package, and that way it would be quite easy to find.

**Comment by naiquevin** [comment]
Hi @andy-maier. Sorry for a very late response. At present `pipdeptree` completely relies on the `pip`'s code that's installed in the env. So the scope is limited to the information that `pip` provides. 

To get the release information, we'd need to use the json api provided by pypi.org. But it may not be as trivial as that because extra index urls will also need to be supported. I will look into this but can't promise anything. 

Also, with the recent improvements in `pip` dependency resolution is now much better. So I am not sure if there's a use case anymore for the conflict and cyclic deps detection functionalities in pipdeptree. Perhaps it's only useful for legacy envs where `pip` can't be upgraded for some reason.

**Comment by gaborbernat** [comment]
This information is not available after installation so we cannot do this.
