### ISSUE TITLE
No dependencies shown for GemGIS

### ISSUE THREAD

**Issue by AlexanderJuestel** [tox-dev/pipdeptree#163]
Hello, 

I was trying to visualize the dependencies of the GemGIS package found here: https://github.com/cgre-aachen/gemgis using

`pipdeptree -p gemgis --graph-output png > dependencies.png`

However, this failed and only a bubble with `gemgis` was returned in the image. I ran the code in an environment where the package and all dependencies were installed. 

Thanks for any tip in advance about what I have been missing here!
Cheers
Alex

**Comment by gaborbernat** [comment]
Can you still replicate this?

**Comment by kdebrab** [comment]
Exporting packages to png seems to be broken in general for me. Exporting to svg still works however.

**Comment by kemzeb** [comment]
https://github.com/cgre-aachen/gemgis/blob/8bb2c7c19d6610da720a865013815dd61d9acd44/setup.py#L16

Not sure if this is the case, but my best guess is because of this line in `gemgis`'s `setup.py` file. It could be the case that because `install_requires` has no dependencies, the pip internals weren't able to find any that relates to `gemgis` during pipdeptree's discovery phase hence why we don't get any dependencies.
