### ISSUE TITLE
Dependency on importlib-metadata

### ISSUE THREAD

**Issue by frenzymadness** [tox-dev/pipdeptree#174]
I was looking at the difference between the last two releases when I realized that the dependency on importlib-metadata (for Python < 3.8) is not listed in the package metadata.

Is that correct?

**Comment by saaketp** [comment]
Yes, it is not a dependency because it works even without importlib-metadata, by falling back to importing the package and looking at `package.__version__`. 

The importlib_metadata path just gives more accurate results because it can handle the cases where `__version__` is not defined and when the package name and the import name are different (and it is probably faster because it avoids the import). The fallback case will give `?` as the version in those cases.

**Comment by frenzymadness** [comment]
All right, thanks for the info.
