### ISSUE TITLE
ImportError: cannot import name 'get_installed_distributions' from 'pip'

### ISSUE THREAD

**Issue by gsmethells** [tox-dev/pipdeptree#232]
Stack trace on Python3.7 even after doing `pip install --upgrade pip`

```
[root@jointsdev8me1 joints]# pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.7/site-packages (23.1.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@jointsdev8me1 joints]# pipdeptree
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pipdeptree.py", line 24, in <module>
    from pip._internal.utils.misc import get_installed_distributions
ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' (/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pipdeptree", line 5, in <module>
    from pipdeptree import main
  File "/usr/local/lib/python3.7/site-packages/pipdeptree.py", line 27, in <module>
    from pip import get_installed_distributions, FrozenRequirement
ImportError: cannot import name 'get_installed_distributions' from 'pip' (/usr/local/lib/python3.7/site-packages/pip/__init__.py)
```

which led me to this topic on Stack Overflow as a possible path forward towards a resolution:

https://stackoverflow.com/questions/49923671/are-there-any-function-replacement-for-pip-get-installed-distributions-in-pip

**Comment by kemzeb** [comment]
Hi @gsmethells, sorry for the late response to this. Looking at the code of pipdeptree==2.9.6 (since this was the last version to support Python v3.7), I see the following [here](https://github.com/pypa/pip/blob/3fe7e54fceac7a03bcb88ce26cfd0937acfe5e40/src/pip/_internal/metadata/pkg_resources.py#L230):
```python
def get_installed_distributions(
    local_only: bool = False,  # noqa: FBT001, FBT002
    user_only: bool = False,  # noqa: FBT001, FBT002
) -> list[DistInfoDistribution]:
    try:
        from pip._internal.metadata import pkg_resources
    except ImportError:
        # For backward compatibility with python ver. 2.7 and pip
        # version 20.3.4 (the latest pip version that works with python
        # version 2.7)
        from pip._internal.utils import misc

        return misc.get_installed_distributions(  # type: ignore[no-any-return,attr-defined]
            local_only=local_only,
            user_only=user_only,
        )
. . .
```

I also see that you installed pip==23.1.2. Looking at the related [code](https://github.com/pypa/pip/blob/3fe7e54fceac7a03bcb88ce26cfd0937acfe5e40/src/pip/_internal/metadata/pkg_resources.py#L222C1) associated to this version, importing `pkg_resources` should have succeeded, but for some reason you seem to get an `ImportError` and we try to instead grab the `get_installed_distributions()` using the older way of retrieving it.

My best guess as to why this happend is that pipdeptree is using the pip provided by your system environment rather than the updated pip you installed. I believe I encountered something like this in the recent past while trying to use older versions of pip in a virtual environment and using `strace` to track the files `pipdeptree` opens when it's executing.

Since I feel like this something we have no control over and this occurred in Python v3.7 (which we no longer support), I'll go ahead and close this issue.
