### ISSUE TITLE
Flag for packages with native components (C, Rust etc.)

### ISSUE THREAD

**Issue by IsakTheHacker** [tox-dev/pipdeptree#293]
It would be excellent if you could add a flag for only showing packages that contain native code (C, C++, Rust etc.). Or just marking the native packages as bold or in another color

**Comment by xiacunshun** [comment]
Can you explain why you need this feature?

**Comment by IsakTheHacker** [comment]
When running Python on a non standard platform such as Android using [Chaquopy](https://github.com/chaquo/chaquopy) it is sometimes needed to use a PyPI package that transitively depends on a package with native code. Since Android is not an officially supported platform by PyPI nor Python itself all native packages that are used in an Android app are required to be built (and patched in some cases) manually using a special tool provided by Chaquopy. I would need this feature to find out which packages I would need to cross compile in order to build my Android app successfully. Would this be possible to implement?

**Comment by kemzeb** [comment]
I believe it would only be a performance problem when we end up using it as an option (e.g. --native or something like that) as only then we would need to recurse through each package's source directory looking for particular source files. This would also mean that we need to keep somehow determine if a file is C++, Java, Rust, etc. I'm unsure how we can do this reliably without having to store all the different file extensions that exist for these langauges.

One other thought I had was using the programming language classifiers that PyPi mentions [here](https://pypi.org/classifiers/). This would make it really easy to determine if a package contains native code as we already have this metadata and we can just search for it. I'm not sure if this is reliable, however, as there could be packages that have, for example, C++ code but don't add the `Programming Language :: C++` classifier.

**Comment by kemzeb** [comment]
I'm going to close as this does seem to be a very specific use case. If a package's classifier metadata were reliable I would have no problem implementing this since this metadata is easily available. However, the only approach I'm seeing right now would be to recurse each package's source directory and look for (and in the future maintain) specific file extensions.

Feel free to fork this repo and add patches to meet your use case if you wish; I'll be more than happy to help you if you have any questions.
