### ISSUE TITLE
`test_custom_interpreter` fails

### ISSUE THREAD

**Issue by mtelka** [tox-dev/pipdeptree#343]
### What pipdeptree version are you using?

2.17.0

### Are you running pipdeptree in a virtual environment?

- [ ] Yes

### Describe the problem

With version `2.17.0` the `test_custom_interpreter` test started to fail:
```
============================= test session starts ==============================
platform sunos5 -- Python 3.9.19, pytest-8.1.1, pluggy-1.4.0 -- $(BUILD_DIR)/.tox/py39/bin/python
cachedir: .tox/py39/.pytest_cache
rootdir: $(BUILD_DIR)
configfile: pyproject.toml
plugins: mock-3.14.0, cov-5.0.0
collecting ... collected 2 items

tests/test_non_host.py::test_custom_interpreter[True] FAILED             [ 50%]
tests/test_non_host.py::test_custom_interpreter[False] FAILED            [100%]

=================================== FAILURES ===================================
________________________ test_custom_interpreter[True] _________________________

tmp_path = PosixPath('/tmp/pytest-of-marcel/pytest-137/test_custom_interpreter_True_0')
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fffacde7130>
capfd = <_pytest.capture.CaptureFixture object at 0x7fffacde7310>
args_joined = True

    @pytest.mark.parametrize("args_joined", [True, False])
    def test_custom_interpreter(
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capfd: pytest.CaptureFixture[str],
        args_joined: bool,
    ) -> None:
        result = virtualenv.cli_run([str(tmp_path / "venv"), "--activators", ""])
        cmd = [sys.executable]
        monkeypatch.chdir(tmp_path)
        py = str(result.creator.exe.relative_to(tmp_path))
        cmd += [f"--python={result.creator.exe}"] if args_joined else ["--python", py]
        monkeypatch.setattr(sys, "argv", cmd)
        main()
        out, _ = capfd.readouterr()
        found = {i.split("==")[0] for i in out.splitlines()}
        implementation = python_implementation()
        if implementation == "CPython":
            expected = {"pip", "setuptools", "wheel"}
        elif implementation == "PyPy":
            expected = {"cffi", "greenlet", "pip", "readline", "setuptools", "wheel"}  # pragma: no cover
        else:
            raise ValueError(implementation)
        if sys.version_info >= (3, 12):
            expected -= {"setuptools", "wheel"}
>       assert found == expected, out
E       AssertionError: pipdeptree==2.17.0
E         ├── packaging [required: >=23.1, installed: 24.0]
E         └── pip [required: >=23.1.2, installed: 24.0]
E         setuptools==69.1.1
E         wheel==0.42.0
E
E       assert {'pipdeptree', '├── packaging [required: >=23.1, installed: 24.0]', 'wheel', '└── pip [required: >=23.1.2, installed: 24.0]', 'setuptools'} == {'pip', 'setuptools', 'wheel'}
E
E         Extra items in the left set:
E         '├── packaging [required: >=23.1, installed: 24.0]'
E         '└── pip [required: >=23.1.2, installed: 24.0]'
E         'pipdeptree'
E         Extra items in the right set:
E         'pip'
E
E         Full diff:
E           {
E         -     'pip',
E         +     'pipdeptree',
E               'setuptools',
E               'wheel',
E         +     '└── pip [required: >=23.1.2, installed: 24.0]',
E         +     '├── packaging [required: >=23.1, installed: 24.0]',
E           }

$(BUILD_DIR)/tests/test_non_host.py:41: AssertionError
________________________ test_custom_interpreter[False] ________________________

tmp_path = PosixPath('/tmp/pytest-of-marcel/pytest-137/test_custom_interpreter_False_0')
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fffacc09d00>
capfd = <_pytest.capture.CaptureFixture object at 0x7fffacc097f0>
args_joined = False

    @pytest.mark.parametrize("args_joined", [True, False])
    def test_custom_interpreter(
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
        capfd: pytest.CaptureFixture[str],
        args_joined: bool,
    ) -> None:
        result = virtualenv.cli_run([str(tmp_path / "venv"), "--activators", ""])
        cmd = [sys.executable]
        monkeypatch.chdir(tmp_path)
        py = str(result.creator.exe.relative_to(tmp_path))
        cmd += [f"--python={result.creator.exe}"] if args_joined else ["--python", py]
        monkeypatch.setattr(sys, "argv", cmd)
        main()
        out, _ = capfd.readouterr()
        found = {i.split("==")[0] for i in out.splitlines()}
        implementation = python_implementation()
        if implementation == "CPython":
            expected = {"pip", "setuptools", "wheel"}
        elif implementation == "PyPy":
            expected = {"cffi", "greenlet", "pip", "readline", "setuptools", "wheel"}  # pragma: no cover
        else:
            raise ValueError(implementation)
        if sys.version_info >= (3, 12):
            expected -= {"setuptools", "wheel"}
>       assert found == expected, out
E       AssertionError: pipdeptree==2.17.0
E         ├── packaging [required: >=23.1, installed: 24.0]
E         └── pip [required: >=23.1.2, installed: 24.0]
E         setuptools==69.1.1
E         wheel==0.42.0
E
E       assert {'pipdeptree', '├── packaging [required: >=23.1, installed: 24.0]', 'wheel', '└── pip [required: >=23.1.2, installed: 24.0]', 'setuptools'} == {'pip', 'setuptools', 'wheel'}
E
E         Extra items in the left set:
E         '├── packaging [required: >=23.1, installed: 24.0]'
E         '└── pip [required: >=23.1.2, installed: 24.0]'
E         'pipdeptree'
E         Extra items in the right set:
E         'pip'
E
E         Full diff:
E           {
E         -     'pip',
E         +     'pipdeptree',
E               'setuptools',
E               'wheel',
E         +     '└── pip [required: >=23.1.2, installed: 24.0]',
E         +     '├── packaging [required: >=23.1, installed: 24.0]',
E           }

$(BUILD_DIR)/tests/test_non_host.py:41: AssertionError
```
This is regression.  When I try the same with version `2.16.2` the test pass as expected.

**Comment by xiacunshun** [comment]
@mtelka Can you give me more infomation(steps) so that I can reproduce it? I tried some kinds of situations but all run well.
According to the logs, it seems that `pipdeptree` is found by accident.
As we noted [here](https://github.com/tox-dev/pipdeptree/blob/main/src/pipdeptree/_non_host.py#L52), current directory(project) which `pipdeptree` and `packaging` are in is added to `sys.path` before the cmd is executed.
```
cwd: Sets the current directory before the child is executed.
```
However, `distribution` scans the `sys.path` only for METADATA file, it may not find the `pipdeptree` and `packaging` under `project`.

**Comment by gaborbernat** [comment]
I feel like we should exclude the sys path of where our project and packaging project lives whenever we are targeting a different python version than the host one, so we don't inject the host Python packages into the tree. Importlib.metadata allows one to specify the path under which to search for packages.

**Comment by xiacunshun** [comment]
> I feel like we should exclude the sys path of where our project and packaging project lives whenever we are targeting a different python version than the host one, so we don't inject the host Python packages into the tree. Importlib.metadata allows one to specify the path under which to search for packages.
> 
> We could pass this information down via some kind of private environment variable, and perhaps even do a query call to the python interpreter to check if the path were passing down or otherwise part of the system path.

That's a good idea. We can get the `prefix` or `sitepackages` from the targeting python interpreter, then we can do the search work directly instead of calling the tool again. I'll make a draft tomorrow.

**Comment by mtelka** [comment]
I still see the same issue with `pipdeptree 2.18.0`.  Please note that I do not run tests in virtual environment.  When I switch to virtual env then all tests pass.

**Comment by xiacunshun** [comment]
@mtelka According to your log, it seems like you are building an rpm?
I tried that with spec file from fedora and found that the site-packages directory where `pipdeptree` is in is added to PYTHONPATH, which is the reason why `pipdeptree` appears in the result.
```
+ PYTHONPATH=/builddir/build/BUILDROOT/python-pipdeptree-2.18.0-1.ocs23.x86_64/usr/lib64/python3.11/site-packages:/builddir/build/BUILDROOT/python-pipdeptree-2.18.0-1.ocs23.x86_64/usr/lib/python3.11/site-packages
```

**Comment by xiacunshun** [comment]
The `sys.path` returns from customer interpreter:
```
['', '/builddir/build/BUILDROOT/python-pipdeptree-2.18.0-1.ocs23.x86_64/usr/lib64/python3.11/site-packages', '/builddir/build/BUILDROOT/python-pipdeptree-2.18.0-1.ocs23.x86_64/usr/lib/python3.11/site-packages', '/usr/lib64/python311.zip', '/usr/lib64/python3.11', '/usr/lib64/python3.11/lib-dynload', '/tmp/pytest-of-root/pytest-6/test_custom_interpreter_False_0/venv/lib64/python3.11/site-packages', '/tmp/pytest-of-root/pytest-6/test_custom_interpreter_False_0/venv/lib/python3.11/site-packages']
```

**Comment by kemzeb** [comment]
> @mtelka According to your log, it seems like you are building an rpm? I tried that with spec file from fedora and found that the site-packages directory where `pipdeptree` is in is added to PYTHONPATH, which is the reason why `pipdeptree` appears in the result.

Looking at the logs, I don't think they are building rpm-based distributions as it looks like the the tests were ran using Solaris (which seems to follow the `pkgtool` format as explained in this Python [doc](https://docs.python.org/3.8/distutils/builtdist.html)).

@mtelka Just to make sure, when you running tests do you modify `$PYTHONPATH`?

If so, then this should be the reason why you are seeing these test failures. In 2.16.2 we would make a copy of the available environment variables, **change** `PYTHONPATH` to point to a temporary directory we created so that the custom interpreter would recognize `pipdeptree` as a module to run, and run it. In 2.17.0 onwards we actually use the environment variables from the current environment (so we **don't modify** `PYTHONPATH`) when we fire up a subprocess to query for paths to search for package metadata (looked [here](https://docs.python.org/3/library/subprocess.html#subprocess.run) for `subprocess` docs).

**Comment by kemzeb** [comment]
> edit: It looks like the macros %pytest did this.

> rpm -E %pytest
\
  CFLAGS="${CFLAGS:-${RPM_OPT_FLAGS}}" LDFLAGS="${LDFLAGS:-${RPM_LD_FLAGS}}"\
  PATH="/root/rpmbuild/BUILDROOT/%{NAME}-%{VERSION}-%{RELEASE}.x86_64/usr/bin:$PATH"\
  PYTHONPATH="${PYTHONPATH:-/root/rpmbuild/BUILDROOT/%{NAME}-%{VERSION}-%{RELEASE}.x86_64/usr/lib64/python3.11/site-packages:/root/rpmbuild/BUILDROOT/%{NAME}-%{VERSION}-%{RELEASE}.x86_64/usr/lib/python3.11/site-packages}"\
  PYTHONDONTWRITEBYTECODE=1\
  \
  /usr/bin/pytest

I do see we have #348 and they have the same test failures as we see in this issue and they are building rpm-based distributions. I do believe that with both of these issues the problem has to do with `$PYTHONPATH` being modified and us supplying it to the custom interpreter (when in the past we modified ourselves before sending it to the child process we create). So for possible solutions:
- Copy all environment variables and remove `$PYTHONPATH` before running the child process. This would make sense to do since we did not honor `$PYTHONPATH` in the past **specifically** when firing up the custom interpreter
- Continue to allow `$PYTHONPATH` to be passed to the child process and change the failing tests by deleting `$PYTHONPATH` (since we know it will be passed to our child process during the test and we don't know what to expect from it)

**Comment by mtelka** [comment]
> > @mtelka According to your log, it seems like you are building an rpm? I tried that with spec file from fedora and found that the site-packages directory where `pipdeptree` is in is added to PYTHONPATH, which is the reason why `pipdeptree` appears in the result.
> 
> Looking at the logs, I don't think they are building rpm-based distributions as it looks like the the tests were ran using Solaris (which seems to follow the `pkgtool` format as explained in this Python [doc](https://docs.python.org/3.8/distutils/builtdist.html)).

I'm packaging for OpenIndiana and we use pkg5 packages (the same as Solaris 11 uses).  The `pkgtool` is for old (traditional) package format used primarily for Solaris 10 and older.
