### ISSUE TITLE
Broken in python 3.10

### ISSUE THREAD

**Issue by soerenwolfers** [tox-dev/pipdeptree#350]
### What pipdeptree version are you using?

2.17.0

### Are you running pipdeptree in a virtual environment?

- [X] Yes

### Describe the problem

Getting 
```
ValueError: Couldn't determine installed packags: Traceback (most recent call last):
...PackageDAG.from_pkgs([x for x in pkgs if PACKAGE_NAME == x.key)
  File "/home/admin/.local/lib/python3.10/site-packages/pipdeptree/_models/dag.py", line 42, in from_pkgs
    dist_pkgs = [DistPackage(p) for p in pkgs]
  File "/home/admin/.local/lib/python3.10/site-packages/pipdeptree/_models/dag.py", line 42, in <listcomp>
    dist_pkgs = [DistPackage(p) for p in pkgs]
  File "/home/admin/.local/lib/python3.10/site-packages/pipdeptree/_models/package.py", line 95, in __init__
    super().__init__(obj.metadata["Name"])
  File "/home/admin/.local/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2903, in __getattr__
    return getattr(self._provider, attr)
AttributeError: 'PathMetadata' object has no attribute 'metadata'
```

python3.10
importlib_metadata==7.1.0
pipdeptree=2.17.0

https://github.com/tox-dev/pipdeptree/blame/main/src/pipdeptree/_models/package.py#L103

**Comment by kemzeb** [comment]
It looks like this is because you are passing a list of `pip._vendor.pkg_resources.DistInfoDistribution` when we now expect `importlib.metadata.Distribution`.

`pip._vendor.pkg_resources.DistInfoDistribution` is a sublcass of `pip._vendor.pkg_resources.Distribution`, and when we try to perform `obj.metadata['Name']`, the `metadata` attribute fails to be looked up, and since the class implements `__getattr__()`, it uses it (see implementation [here](https://github.com/pypa/pip/blob/550388eb03eeb0746b9503a93ab9ac224d27bb58/src/pip/_vendor/pkg_resources/__init__.py#L2874)). It delegates attribute lookup to `self._provider`, but since `metadata` doesn't exist here either we will see the failure.

Looking at the stack trace further, it looks like you are using our API. Sadly, this is internal API and therefore may change in future releases.

**Comment by kemzeb** [comment]
I don't recommend you continue using the API, but if you really need it I think I see three options:
- Stick with pipdeptree==2.16.2
- Use pipdeptree==2.16.2 until you make the necessary changes to pass `importlib.metadata.Distribution` objects
- Wrap each `pip._vendor.pkg_resources.DistInfoDistribution` object in another class that inherits from `importlib.metadata.Distribution` and implements its abstract methods (see [here](https://github.com/python/cpython/blob/26831278d85761bd33975a7503fbf42b42eae91d/Lib/importlib/metadata/__init__.py#L365))

**Comment by soerenwolfers** [comment]
Thanks for the quick response. Will probably change tooling, I really do need a stable API, not a command line tool
